apiVersion: v1
kind: Service
metadata:
  name: leave-management-service
  labels:
    app: leave-management
spec:
  type: LoadBalancer
  selector:
    app: leave-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
      name: http
